import { Themes } from '@varlet/ui'

export const darkTheme = Themes.toViewport({
  // varlet
  ...Themes.md3Dark,
  '--hsl-secondary': 'var(--hsl-inverse-surface)',
  '--color-secondary': 'hsla(var(--hsl-secondary), 1)',
  '--hsl-tertiary': 'var(--hsl-on-surface-variant)',
  '--color-tertiary': 'hsla(var(--hsl-tertiary), 1)',
  '--hsl-muted': '264, 5%, 58%',
  '--color-muted': 'hsla(var(--hsl-muted), 1)',
  '--hsl-primary': '34.44, 100%, 57.65%',
  '--color-primary': 'hsla(var(--hsl-primary), 1)',
  '--hsl-on-primary': '215, 100%, 22%',
  '--color-on-primary': 'hsla(var(--hsl-on-primary), 1)',
  '--hsl-primary-container': '218, 71%, 33%',
  '--color-primary-container': 'hsla(var(--hsl-primary-co ntainer), 1)',
  '--hsl-on-primary-container': '226, 100%, 93%',
  '--color-on-primary-container': 'hsla(var(--hsl-on-primary-container), 1)',
  '--hsl-info': '227, 29%, 81%',
  '--color-info': 'hsla(var(--hsl-info), 1)',
  '--hsl-on-info': '223, 23%, 21%',
  '--color-on-info': 'hsla(var(--hsl-on-info), 1)',
  '--hsl-info-container': '226, 16%, 30%',
  '--color-info-container': 'hsla(var(--hsl-info-container), 1)',
  '--hsl-on-info-container': '228, 71%, 92%',
  '--color-on-info-container': 'hsla(var(--hsl-on-info-container), 1)',
  '--hsl-warning': '303, 37%, 81%',
  '--color-warning': 'hsla(var(--hsl-warning), 1)',
  '--hsl-on-warning': '298, 26%, 21%',
  '--color-on-warning': 'hsla(var(--hsl-on-warning), 1)',
  '--hsl-warning-container': '298, 19%, 30%',
  '--color-warning-container': 'hsla(var(--hsl-warning-container), 1)',
  '--hsl-on-warning-container': '305, 90%, 92%',
  '--color-on-warning-container': 'hsla(var(--hsl-on-warning-container), 1)',
  '--hsl-danger': '6, 100%, 84%',
  '--color-danger': 'hsla(var(--hsl-danger), 1)',
  '--hsl-on-danger': '357, 100%, 21%',
  '--color-on-danger': 'hsla(var(--hsl-on-danger), 1)',
  '--hsl-danger-container': '356, 100%, 29%',
  '--color-danger-container': 'hsla(var(--hsl-danger-container), 1)',
  '--hsl-on-danger-container': '6, 100%, 84%',
  '--color-on-danger-container': 'hsla(var(--hsl-on-danger-container), 1)',
  '--hsl-body': '240, 7%, 11%',
  '--color-body': 'hsla(var(--hsl-body), 1)',
  '--hsl-text': '255, 7%, 89%',
  '--color-text': 'hsla(var(--hsl-text), 1)',
  '--hsl-on-surface-variant': '235, 10%, 79%',
  '--color-on-surface-variant': 'hsla(var(--hsl-on-surface-variant), 1)',
  '--hsl-outline': '234, 5%, 58%',
  '--color-outline': 'hsla(var(--hsl-outline), 1)',
  '--hsl-inverse-surface': '255, 7%, 89%',
  '--color-inverse-surface': 'hsla(var(--hsl-inverse-surface), 1)',
})
