import { Themes } from '@varlet/ui'

export const lightTheme = Themes.toViewport({
  // varlet
  ...Themes.md3Light,
  '--hsl-secondary': '264, 8%, 12%',
  '--color-secondary': 'hsla(var(--hsl-secondary), 1)',
  '--hsl-tertiary': 'var(--hsl-on-surface-variant)',
  '--color-tertiary': 'hsla(var(--hsl-tertiary), 1)',
  '--hsl-muted': '270, 4%, 47%',
  '--color-muted': 'hsla(var(--hsl-muted), 1)',
  '--hsl-primary': '34, 100%, 58%',
  '--color-primary': 'hsla(var(--hsl-primary), 1)',
  '--hsl-on-primary': '0, 0%, 100%',
  '--color-on-primary': 'hsla(var(--hsl-on-primary), 1)',
  '--hsl-primary-container': '226, 100%, 93%',
  '--color-primary-container': 'hsla(var(--hsl-primary-container), 1)',
  '--hsl-on-primary-container': '218, 100%, 13%',
  '--color-on-primary-container': 'hsla(var(--hsl-on-primary-container), 1)',
  '--hsl-info': '224, 13%, 39%',
  '--color-info': 'hsla(var(--hsl-info), 1)',
  '--hsl-on-info': '0, 0%, 100%',
  '--color-on-info': 'hsla(var(--hsl-on-info), 1)',
  '--hsl-info-container': '228, 71%, 92%',
  '--color-info-container': 'hsla(var(--hsl-info-container), 1)',
  '--hsl-on-info-container': '223, 38%, 13%',
  '--color-on-info-container': 'hsla(var(--hsl-on-info-container), 1)',
  '--hsl-warning': '300, 15%, 39%',
  '--color-warning': 'hsla(var(--hsl-warning), 1)',
  '--hsl-on-warning': '0, 0%, 100%',
  '--color-on-warning': 'hsla(var(--hsl-on-warning), 1)',
  '--hsl-warning-container': '305, 90%, 92%',
  '--color-warning-container': 'hsla(var(--hsl-warning-container), 1)',
  '--hsl-on-warning-container': '295, 40%, 12%',
  '--color-on-warning-container': 'hsla(var(--hsl-on-warning-container), 1)',
  '--hsl-danger': '0, 75%, 42%',
  '--color-danger': 'hsla(var(--hsl-danger), 1)',
  '--hsl-on-danger': '0, 0%, 100%',
  '--color-on-danger': 'hsla(var(--hsl-on-danger), 1)',
  '--hsl-danger-container': '6, 100%, 92%',
  '--color-danger-container': 'hsla(var(--hsl-danger-container), 1)',
  '--hsl-on-danger-container': '358, 100%, 13%',
  '--color-on-danger-container': 'hsla(var(--hsl-on-danger-container), 1)',
  '--hsl-body': '285, 100%, 99%',
  '--color-body': 'hsla(var(--hsl-body), 1)',
  '--hsl-text': '240, 7%, 11%',
  '--color-text': 'hsla(var(--hsl-text), 1)',
  '--hsl-on-surface-variant': '229, 7%, 29%',
  '--color-on-surface-variant': 'hsla(var(--hsl-on-surface-variant), 1)',
  '--hsl-outline': '229, 4%, 48%',
  '--color-outline': 'hsla(var(--hsl-outline), 1)',
  '--hsl-inverse-surface': '240, 4%, 20%',
  '--color-inverse-surface': 'hsla(var(--hsl-inverse-surface), 1)',
})
