name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - feature/wjl

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"  # 设置 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:preview

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # 部署到 gh-pages 分支
          folder: /docs      # 构建输出目录 dist
